/**
 * The single data-access module. No component fetches a URL directly.
 *
 * Today every payload is a static JSON file generated by the monthly batch job.
 * A pure static site cannot enforce a paywall - anyone can request the JSON -
 * so front-end gating over public JSON would be decoration, not access control.
 * The point of routing every read through here is that moving the gated payload
 * behind an authenticated endpoint (a Cloudflare Worker or a Vercel function
 * checking a session) becomes a change to this file alone, not a rewrite.
 *
 * Tier boundary, already present in the data model:
 *   scores_public.json - ranked list only (the free hook)
 *   scores_full.json   - factor scores, every sub-metric, provenance (the asset)
 */
import type { CoverageReport, HistoryIndex, ScoresPayload, StockRow } from "./types";

const BASE = `${import.meta.env.BASE_URL}data`;

export type Tier = "public" | "full";

/** Which payload the app reads. Flip to "public" to exercise the free tier. */
const TIER: Tier = "full";

async function fetchJson<T>(file: string): Promise<T> {
  const res = await fetch(`${BASE}/${file}`, { cache: "no-cache" });
  if (!res.ok) {
    throw new Error(`Could not load ${file} (HTTP ${res.status}). Has the batch job run?`);
  }
  return (await res.json()) as T;
}

/** Promise-level memoisation: many components ask for the same payload during
 *  the first render, and they should share one request. */
const cache = new Map<string, Promise<unknown>>();

function once<T>(key: string, load: () => Promise<T>): Promise<T> {
  if (!cache.has(key)) cache.set(key, load());
  return cache.get(key) as Promise<T>;
}

export function loadScores(): Promise<ScoresPayload> {
  const file = TIER === "full" ? "scores_full.json" : "scores_public.json";
  return once(file, () => fetchJson<ScoresPayload>(file));
}

export function loadHistoryIndex(): Promise<HistoryIndex> {
  return once("history_index.json", async () => {
    try {
      return await fetchJson<HistoryIndex>("history_index.json");
    } catch {
      // Run 1 may not have an index yet. An empty index renders the honest
      // "history begins accumulating" state rather than a fake flat line.
      return { months: [], observations: 0, tickers: {} };
    }
  });
}

export function loadCoverage(): Promise<CoverageReport> {
  return once("coverage_report.json", () => fetchJson<CoverageReport>("coverage_report.json"));
}

/** All scored rows across every segment, in one flat list. */
export async function loadAllRows(): Promise<StockRow[]> {
  const payload = await loadScores();
  return Object.values(payload.segments).flat();
}

export async function loadStock(ticker: string): Promise<StockRow | undefined> {
  const rows = await loadAllRows();
  return rows.find((r) => r.ticker === ticker.toUpperCase());
}

/**
 * Privacy-respecting analytics hook, deliberately not wired to anything.
 * Plausible-compatible: when a script defines `window.plausible`, events flow;
 * otherwise this is a no-op. No cookies, no identifiers, no payload beyond the
 * event name and plain props.
 */
type PlausibleWindow = Window & { plausible?: (event: string, opts?: { props: Record<string, string> }) => void };

export function track(event: string, props: Record<string, string> = {}): void {
  const w = window as PlausibleWindow;
  if (typeof w.plausible === "function") w.plausible(event, { props });
}
